In [ ]:
# (1) a. Импортируйте библиотеку NumPy
import numpy as np

In [ ]:
# (2) b. Создайте массив из 10 нулей
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# (3) d. Создать массив из 10 пятерок
a = np.arange(10)
a[:] = 5
print(a)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
# (4) e. Создать массив из целых чисел от 10 до 50
a = np.arange(10, 51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# (5) f. Создать массив из четных чисел от 10 до 50
a = np.arange(10, 51, 2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# (6) g. Создать матрицу 3х3 с числами от 0 до 8
a = np.arange(0,9)
b = a.reshape(3,3)
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# (7) h.Создать единичную матрицу 3x3
a = np.ones(9)
b = a.reshape(3,3)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# (8) i.Используйте NumPy для генерации случайного числа от 0 до 1
a = np.random.rand()
print(a)

0.6704186795654703


In [ ]:
# (9) j. Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
a = np.random.normal(0,1,25)
print(a)

[-1.09756365  0.59729223 -0.86111834 -0.97536302 -1.06717312  0.98700512
 -0.42569197  0.02113285 -0.21541673  0.74226578 -0.34797842  1.364697
 -0.27657684  0.42218855 -0.53440728 -0.60015452 -0.7051762   1.8150929
 -0.51547191  0.49473622  1.2703846   0.91080933 -0.77830346  0.76505181
  0.29164118]


In [ ]:
# (10) k. Создайте следующую матрицу используя функции библиотеки NumPy
a = np.arange(1,101).reshape(10,10)
print(a / 100)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
# (11) l. Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах
# это наша стартовая матрица
# Необходимо написать код который вернет следующую матрицуиз стартовой:
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('--------')
print(mat[2:,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
--------
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# (12) m. Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------')
print(mat[3,4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------
20


In [ ]:
# (13) n. Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------')
a = mat[0:3,1]
print(a.reshape(3,1))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------
[[ 2]
 [ 7]
 [12]]


In [ ]:
# (14) o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------')
print(mat[4:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------
[[21 22 23 24 25]]


In [ ]:
# (15) p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------')
print(mat[3:])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------
[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# (16) q. Получить сумму всех значений в стартовой матрице mat
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------')
print(mat.sum())


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------
325


In [ ]:
# (17) r.Получить стандартное отклонение в стартовой матрице mat
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------')
print(mat.std())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------
7.211102550927978


In [ ]:
# (18) s.Получить сумму значений в колонках в стартовой матрице mat
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------')
print(mat.sum(axis = 0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------
[55 60 65 70 75]
